# ── Meloworld Hyprlock Config ──────────────────────────

background {
    monitor =
    path = $HOME/.config/hypr/wallpaper.jpeg
    blur_passes = 2
    blur_size = 5
    brightness = 0.8
}

# ── Top Bar (Clock Pill) ──────────────────────────────

shape {
    monitor =
    size = 95, 40
    color = rgba(33, 33, 33, 1)
    rounding = 8
    position = 0, -8
    halign = center
    valign = top
}

shape {
    monitor =
    size = 82, 28
    color = rgba(ffffddff)
    rounding = 5
    position = 0, -14
    halign = center
    valign = top
}

label {
    monitor =
    text =  $TIME
    color = rgb(21, 21, 21)
    font_size = 12
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -16
    halign = center
    valign = top

}

# ── Center Card Layout ────────────────────────────────
# User Label (mimicking the active user row)

# Outer card
shape {
    size = 340, 136
    color = rgb(33, 33, 33)
    border_color = rgb(80cbc4)
    border_size = 3
    rounding = 8
    position = 0, 24
    halign = center
    valign = center
}

# Username row background
shape {
    size = 300, 40
    color = rgba(3a3a3aff)
    rounding = 8
    position = 0, 50
    halign = center
    valign = center
}

# Password field placeholder
# shape {
#     size = 295, 35
#     color = rgba(2a2a2aff)
#     rounding = 6
#     pos = 0, 0
#     halign = center
#     valign = center
# }


label {
    monitor =
    text =  $USER
    color = rgb(80cbc4)
    font_size = 11
    font_family = JetBrainsMono Nerd Font Bold
    position = -90, 51
    halign = center
    valign = center
}

# Password Input (The SDDM Card Field)
input-field {
    monitor =
    size = 295, 35
    outline_thickness = 3
    dots_size = 0.16
    dots_spacing = 0.8
    outer_color = rgb(80cbc4)
    inner_color = rgb(33, 33, 33)
    font_color = rgb(255, 255, 255)
    font_family = JetBrainsMono Nerd Font Regular
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = rgb(80cbc4)
    fail_color = rgb(ef9a9a)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(fff59d)
    rounding = 6
    position = 0, 0
    halign = center
    valign = center
}
