# ── Meloworld Hyprlock Config ──────────────────────────

background {
    monitor =
    path = /home/melatonia/Pictures/Wallpapers/The Wind Rises.jpeg
    blur_passes = 3
    blur_size = 7
    brightness = 0.6
}

# ── Top Bar (Clock Pill) ──────────────────────────────
label {
    monitor =
    text = cmd[update:1000] echo " $(date +'%H:%M')"
    color = rgb(21, 21, 21)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -12
    halign = center
    valign = top

}

# ── Center Card Layout ────────────────────────────────
# User Label (mimicking the active user row)
label {
    monitor =
    text =  $USER
    color = rgb(80cbc4)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -60
    halign = center
    valign = center
}

# Password Input (The SDDM Card Field)
input-field {
    monitor =
    size = 380, 50
    outline_thickness = 4
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgb(80cbc4)
    inner_color = rgb(33, 33, 33)
    font_color = rgb(255, 255, 255)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = rgb(80cbc4)
    fail_color = rgb(ef9a9a)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(fff59d)
    rounding = 12
    position = 0, -120
    halign = center
    valign = center
}
