background {
    monitor =
    path = /home/melatonia/Pictures/Wallpapers/The Wind Rises.jpeg
    blur_passes = 3
    blur_size = 7
    brightness = 0.6
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgb(80cbc4)
    inner_color = rgb(212121)
    font_color = rgb(ffffff)
    fade_on_empty = true
    placeholder_text = <i>Password</i>
    hide_input = false
    check_color = rgb(80cbc4)
    fail_color = rgb(ef9a9a)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(fff59d)
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(255, 255, 255, 0.9)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(80cbc4ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(255, 255, 255, 0.7)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 130
    halign = center
    valign = center
}
