general {
    ignore_dbus_inhibit = false
}

listener {
    timeout    = 300
    on-timeout = quickshell -c ~/.config/quickshell/idle-overlay
}

listener {
    timeout    = 600
    on-timeout = qs -p ~/.config/quickshell/lockscreen
}

listener {
    timeout    = 900
    on-timeout = systemctl suspend
}
