[General]
# Path to the wallpaper
# Relative to the theme directory or absolute path
background=assets/wallpaper.jpeg

# Font family
font=JetBrainsMono Nerd Font

# Color palette
background_color=#212121
accent_color=#80cbc4
urgent_color=#ef9a9a
